from .shufflenetv2_multi_task import shufflenet_v2_x1_0 as multi_task_shufflenet_v2_x1_0
from .shufflenetv2_segmantation import shufflenet_v2_x1_0 as segmentation_shufflenet_v2_x1_0

from .shufflenetv2 import shufflenet_v2_x1_0
from .bas_seg_net import bas_seg_net_v1
from .shufflenetv2_embedding import shufflenet_v2_x1_0 as embedding_shufflenet_v2_x1_0