crop: False
change_colorspace: False
contrast_normalization: False
gaussian_noise: False
multiply: False
scale: False
rotate: False
shear: False
grayscale: False
hue_and_saturation: False
flip_left_right: False
flip_up_down: False
