project                   : hrsf_Al_1_seg
net                       : segmentation_shufflenet_v2_x1_0
task_type                 : segmentation

classes                   : 3
data_root                 : '/home/lee/data/huaruenshuenfeng/数据/铝片工位一分割'
input_w                   : 288
input_h                   : 320
batch_size                : 64
start_epoch               : 0
epochs                    : 50
balance_n_classes         : 1
balance_n_samples         : 64
resume                    : project/hrsf_Al_1_seg/weights/checkpoint.pth.tar
device                    : gpu
workers                   : 8
seed                      : 0
lr                        : 0.01
criterion_list            : [PeriodLoss]
threshold                 : 0.5
gpus                      : 0
class_weight              : [0.5,0.25,0.25]

augment:
  crop                    : False
  change_colorspace       : True
  contrast_normalization  : True
  gaussian_noise          : False
  multiply                : True
  scale                   : True
  rotate                  : True
  shear                   : False
  grayscale               : False
  hue_and_saturation      : True
  flip_left_right         : True
  flip_up_down            : True

