project: xxx
net: shufflenetv2
task_type: classification

classes: 2
data_root:
image_w: 320
image_h: 192
batch_size: 128
start_epoch: 0
epochs: 50
balance_n_classes: 2
balance_n_samples: 64
resume: model/checkpoint.pth.tar
device: gpu
worker: 8
seed: 0
lr: 0.001
loss: FocalLoss
threshold: 0.5
gpu: 0
class_weight: None

augment:
  crop: False
  change_colorspace: False
  contrast_normalization: False
  gaussian_noise: False
  multiply: True
  scale: True
  rotate: True
  shear: False
  grayscale: False
  hue_and_saturation: True
  flip_left_right: True
  flip_up_down: True

