project:
net: shufflenet_v2_x1_0
task_type: embedding-classification

classes: 11
data_root: /home/lee/params/shuangjing/params
input_w: 320
input_h: 192
batch_size: 128
start_epoch: 0
epochs: 50
balance_n_classes: 8
balance_n_samples: 16
resume: model/checkpoint.pth.tar
device: gpu
worker: 8
seed: 0
lr: 0.001
criterion_list: [ FocalLoss ]
threshold: 0.5
gpus: 0
class_id_map_save_path: temp/class_id_map.txt
class_weight: None

augment:
  crop: False
  change_colorspace: False
  contrast_normalization: False
  gaussian_noise: False
  multiply: True
  scale: True
  rotate: True
  shear: False
  grayscale: False
  hue_and_saturation: True
  flip_left_right: True
  flip_up_down: True

