project: xxx
net: segmentation_shufflenet_v2_x1_0
task_type: segmentation

classes: 3
data_root:
image_w: 320
image_h: 192
batch_size: 64
start_epoch: 0
epochs: 30
balance_n_classes: 1
balance_n_samples: 64
resume: model/checkpoint.pth.tar
device: gpu
worker: 8
seed: 0
lr: 0.008
criterion_list: [ PeriodLoss ]
gpu: 0
class_weight: None
#class_weight: [ 0.5,0.25,0.25 ] #lv
#class_weight: [ 0.4,0.3,0.3 ] #zuo
#class_weight: [ 0.6,0.4 ] #zuo

period_thresh: 0.75
period_n_min: 10000
asymmetry_id: False
convert_float_flag: False
remove_no_json_sample_flag: False
class_id_map_save_path: temp/class_id_map.txt
score_threshold: 0.1
train_outputs: [0]
area_threshold: 100
cycle_train_times:  1

augment:
  crop: False
  change_colorspace: False
  contrast_normalization: False
  gaussian_noise: False
  multiply: True
  scale: True
  rotate: True
  shear: False
  grayscale: False
  hue_and_saturation: True
  flip_left_right: True
  flip_up_down: True

